# Generated by Django 6.0.5 on 2026-06-02 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Рейтинг')),
                ('duration', models.CharField(max_length=20, verbose_name='Длительность')),
                ('quality', models.CharField(choices=[('4K', '4K'), ('HD', 'HD'), ('SD', 'SD')], default='HD', max_length=5, verbose_name='Качество')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/', verbose_name='Миниатюра')),
                ('backdrop', models.ImageField(blank=True, upload_to='backdrops/', verbose_name='Задний фон')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='URL миниатюры')),
                ('backdrop_url', models.URLField(blank=True, verbose_name='URL заднего фона')),
                ('video_file', models.FileField(blank=True, upload_to='videos/', verbose_name='Видео файл')),
                ('video_url', models.URLField(blank=True, verbose_name='URL видео')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('studio', models.CharField(blank=True, max_length=100, verbose_name='Студия')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярное')),
                ('is_hero', models.BooleanField(default=False, verbose_name='Показать в слайдере')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='videos.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(blank=True, to='videos.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер сезона')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='videos.video', verbose_name='Сериал')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
                'ordering': ['number'],
                'unique_together': {('video', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер эпизода')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('duration', models.CharField(blank=True, max_length=20, verbose_name='Длительность')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='URL миниатюры')),
                ('video_file', models.FileField(blank=True, upload_to='episodes/', verbose_name='Видео файл')),
                ('video_url', models.URLField(blank=True, verbose_name='URL видео')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='videos.season', verbose_name='Сезон')),
            ],
            options={
                'verbose_name': 'Эпизод',
                'verbose_name_plural': 'Эпизоды',
                'ordering': ['number'],
                'unique_together': {('season', 'number')},
            },
        ),
    ]
